name: lengua_de_senas
description: "Lengua de Señas"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  #Acceso a Sistema de Archivos
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.8
  #Camara y Video   [subir image_picker: ^0.8.9+2]
  image_picker: ^0.8.7+2
  video_player: ^2.6.1
  #Procesamiento de Video FFMPEG para extraer Frames
  #flutter_ffmpeg: ^0.4.0
  ffmpeg_kit_flutter: ^6.0.3
  #ffmpeg_kit_flutter:
   # git:
    #  url: https://github.com/tanersener/ffmpeg-kit.git #-flutter.git
     # path: flutter/flutter/lib/ffmpeg_kit #flutter/ffmpeg-kit-flutter
  #Prediccion de Video con TensorFlow Lite
  tflite_flutter: ^0.11.0
  #Procesamiento de Imágenes
  image: ^4.2.0
  #Permisos de Camara y Almacenamiento
  permission_handler: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/modelo_lengua_senas.tflite

