name: lengua_de_senas
description: "Lengua de Señas"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  #Acceso a Sistema de Archivos
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.8
  #Camara y Video   [subir image_picker: ^0.8.9+2]
  image_picker: ^0.8.7+2
  video_player: ^2.6.1
  #Procesamiento de Video FFMPEG para extraer Frames
  #flutter_ffmpeg: ^0.4.0
  #ffmpeg_kit_flutter: ^6.0.3
  #ffmpeg_kit_flutter_new: ^2.0.0
  ffmpeg_kit_flutter_minimal: ^6.0.8
  #Prediccion de Video con TensorFlow Lite
  tflite_flutter: ^0.11.0
  #Procesamiento de Imágenes
  image: ^4.2.0
  #Permisos de Camara y Almacenamiento
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Icono de la Aplicacion
  flutter_launcher_icons: ^0.14.4

# Colocar el icono de la aplicacion
flutter_launcher_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/modelo_lengua_senas.tflite
    - assets/logo.png

